// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id: 'us-east-2:4e13dfd9-2040-493f-80f4-9e879fe17ac5',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_I1CjuRgl7',
  aws_user_pools_web_client_id: '78pd4qrph9ij09k0js47igib04',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://zvzxgmuy3ndklk7u4dqzuxxpgq.appsync-api.us-east-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'hackathon-dev',
  aws_user_files_s3_bucket_region: 'us-east-2'
};

export default awsmobile;
